---
# Values file for devnet deploys.
ingress:
  enabled: true
  hosts:
    # The Tendermint RPC port.
    rpc: rpc.devnet.penumbra.zone
    # The pd gRPC port.
    grpc: grpc.devnet.penumbra.zone
    # The Grafana HTTP web interface, for viewing dashboards.
    grafana: grafana.devnet.penumbra.zone

# Set lower SSD requests; default is 100Gi; we'll do a tenth that
# for bespoke sandbox environments like 'devnet'.
persistence:
  size: 10Gi
